import type { BodegaCatTheme } from './types';

export const bodegaCatTheme: BodegaCatTheme = {
  id: 'bodegacat',
  name: 'Bodega Cat',
  description: 'Clean blue and gray theme with amber accents',
  author: 'Bodega Cat',
  version: '1.0.0',
  variables: {
    '--color-primary': '#3B82F6',
    '--color-secondary': '#6B7280',
    '--color-accent': '#F59E0B',
    '--color-background': '#FFFFFF',
    '--color-surface': '#F9FAFB',
    '--color-text': '#111827',
    '--color-text-secondary': '#6B7280',
    '--color-navbar-bg': '#FFFFFF',
    '--color-navbar-text': '#111827',
    '--color-hero-from': '#3B82F6',
    '--color-hero-to': '#F59E0B',
    '--color-footer-bg': '#F9FAFB',
    '--color-footer-text': '#111827',
    '--color-footer-text-muted': '#6B7280',
    '--color-footer-border': '#E5E7EB',
    '--color-cta-from': '#3B82F6',
    '--color-cta-to': '#F59E0B',
    '--font-heading': '"Inter", system-ui, sans-serif',
    '--font-body': '"Inter", system-ui, sans-serif',
    '--border-radius': '0.5rem',
    '--spacing-xs': '0.25rem',
    '--spacing-sm': '0.5rem',
    '--spacing-md': '1rem',
    '--spacing-lg': '1.5rem',
    '--spacing-xl': '2rem',
  },
};
