import type { BodegaCatTheme, ThemeSettingField } from "./types";

const radiusOptions = [
  { value: "0", label: "None" },
  { value: "0.25rem", label: "Small" },
  { value: "0.5rem", label: "Medium" },
  { value: "0.75rem", label: "Large" },
  { value: "1rem", label: "Extra Large" },
  { value: "9999px", label: "Pill" },
];

/** Fields the Void Kitten homepage and catalog read. */
const settings: ThemeSettingField[] = [
  { type: "image", id: "logo", label: "Logo" },
  {
    type: "text",
    id: "contactEmail",
    label: "Contact email",
    placeholder: "hello@example.com",
  },
  {
    type: "text",
    id: "homeHeadline",
    label: "Homepage headline",
    help: "Large heading on the homepage. Leave blank to use the store name.",
  },
  {
    type: "text",
    id: "shopTagline",
    label: "Shop page tagline",
    help: "Line under the shop heading.",
  },
  { type: "text", id: "aboutTitle", label: "About title" },
  { type: "textarea", id: "aboutText", label: "About text" },
  {
    type: "links",
    id: "footerLinks",
    label: "Footer links",
    help: "Label and path or URL.",
  },
  {
    type: "links",
    id: "socialLinks",
    label: "Social links",
    help: "Label and profile URL.",
  },
  {
    type: "color",
    id: "primary",
    label: "Primary",
    variable: "--color-primary",
  },
  {
    type: "color",
    id: "secondary",
    label: "Secondary",
    variable: "--color-secondary",
  },
  { type: "color", id: "accent", label: "Accent", variable: "--color-accent" },
  {
    type: "color",
    id: "background",
    label: "Background",
    variable: "--color-background",
  },
  {
    type: "color",
    id: "surface",
    label: "Surface",
    variable: "--color-surface",
  },
  { type: "color", id: "text", label: "Text", variable: "--color-text" },
  {
    type: "text",
    id: "fontHeading",
    label: "Heading font",
    variable: "--font-heading",
  },
  {
    type: "text",
    id: "fontBody",
    label: "Body font",
    variable: "--font-body",
  },
  {
    type: "select",
    id: "borderRadius",
    label: "Border radius",
    variable: "--border-radius",
    options: radiusOptions,
  },
];

export const voidKittenTheme: BodegaCatTheme = {
  id: "voidkitten",
  name: "Void Kitten",
  description: "Dark mode theme with blue and amber accents",
  author: "Bodega Cat",
  version: "1.0.0",
  variables: {
    "--color-primary": "#60A5FA",
    "--color-secondary": "#9CA3AF",
    "--color-accent": "#FBBF24",
    "--color-background": "#111827",
    "--color-surface": "#1F2937",
    "--color-text": "#F9FAFB",
    "--color-text-secondary": "#D1D5DB",
    "--color-navbar-bg": "#0F172A",
    "--color-navbar-text": "#F9FAFB",
    "--color-hero-from": "var(--color-primary)",
    "--color-hero-to": "var(--color-accent)",
    "--color-footer-bg": "#0F172A",
    "--color-footer-text": "#F9FAFB",
    "--color-footer-text-muted": "#9CA3AF",
    "--color-footer-border": "#374151",
    "--color-cta-from": "#1E3A5F",
    "--color-cta-to": "#374151",
    "--font-heading": '"Inter", system-ui, sans-serif',
    "--font-body": '"Inter", system-ui, sans-serif',
    "--border-radius": "0.5rem",
    "--spacing-xs": "0.25rem",
    "--spacing-sm": "0.5rem",
    "--spacing-md": "1rem",
    "--spacing-lg": "1.5rem",
    "--spacing-xl": "2rem",
  },
  settings,
};
